import test from 'node:test';
import assert from 'node:assert/strict';
import {loadResearchImpact,readResearchImpact} from '../src/research-impact.ts';

const runId='00000000-0000-4000-8000-000000000001',sourceId='paper_123',sourceDigest='a'.repeat(64),projectId='b'.repeat(64);
const expected={runId,sourceId,sourceDigest};
const packet=()=>({schema:'research-source-impact/1',scope:'RECORDED_DIRECT_ONLY',anchor:{run_id:runId,project_id:projectId,source_id:sourceId,source_digest:sourceDigest},candidate_count:1,candidates:[{run_id:'00000000-0000-4000-8000-000000000002',created_at:'2026-09-30T00:00:00Z',status:'COMPLETE',asset:'MOC',nct_id:'NCT00000001',source_title:'MOC paper',uses:[{kind:'REVIEW_FINDING',reference_count:1},{kind:'REVIEW_INPUT_PRIORITY',reference_count:1}]}],caveats:['저장된 직접 source ID 참조만 포함합니다.','인벤토리만으로는 포함하지 않습니다.','research_links는 provenance입니다.','다운스트림 산출물은 추적하지 않습니다.','인증이나 테넌트 격리가 아닙니다.','SOURCE RECORD 지문이며 PDF 바이트 지문이 아닙니다.']});

test('strict reader binds exact run, source and SOURCE RECORD digest',()=>{const value=packet();assert.equal(readResearchImpact(value,expected).candidate_count,1);for(const patch of [{runId:expected.runId.replace('0001','0009')},{sourceId:'other'},{sourceDigest:'c'.repeat(64)}])assert.throws(()=>readResearchImpact(value,{...expected,...patch}),/불일치/);});
test('strict reader rejects malformed counts, unknown fields, duplicates and missing caveats',()=>{for(const mutate of [v=>v.candidate_count=2,v=>v.extra=true,v=>v.candidates[0].extra=true,v=>v.candidates.push(structuredClone(v.candidates[0])),v=>v.candidates[0].uses[0].reference_count=0,v=>v.caveats=[]]){const value=packet();mutate(value);assert.throws(()=>readResearchImpact(value,expected));}});
test('empty result remains an honest zero-candidate response',()=>{const value=packet();value.candidate_count=0;value.candidates=[];assert.equal(readResearchImpact(value,expected).candidates.length,0);});
test('loader sends exact query and maps missing source, version and failed lookup',async()=>{let path='';const loaded=await loadResearchImpact(expected,new AbortController().signal,async(url,options)=>{path=String(url);assert.equal(options.cache,'no-store');return Response.json(packet());});assert.equal(loaded.scope,'RECORDED_DIRECT_ONLY');assert.match(path,/source_id=paper_123&source_digest=/);for(const [status,detail,message] of [[404,'RESEARCH_NOT_FOUND','기준 조사 실행'],[404,'RESEARCH_SOURCE_NOT_FOUND','이 출처'],[409,'RESEARCH_SOURCE_VERSION_MISMATCH','출처 버전'],[500,'IMPACT_LOOKUP_FAILED','확인하지 못했습니다']])await assert.rejects(loadResearchImpact(expected,new AbortController().signal,()=>Response.json({detail},{status})),new RegExp(message));});
test('response for a previous selection is rejected as stale',async()=>{const next={...expected,sourceId:'paper_999'};await assert.rejects(loadResearchImpact(next,new AbortController().signal,()=>Response.json(packet())),/불일치/);});
test('aborted request remains aborted for stale-response handling',async()=>{const controller=new AbortController();controller.abort();await assert.rejects(loadResearchImpact(expected,controller.signal,(_url,options)=>fetch('data:application/json,{}',options)),{name:'AbortError'});});
