import {createContext,useContext,useEffect,useRef,useState,type FormEvent,type ReactNode} from "react";
import {Alert,Button,CircularProgress,TextField} from "@mui/material";
import BrandLogo from "./BrandLogo";
import {expiryDelay,sessionIdentity} from "./access-session";
import {accessMode,clearExpectedSession,currentSession,login,logout,setExpectedSession,type AccessModePacket,type SessionPacket} from "./auth-client";

type Status="checking"|"legacy"|"locked"|"ready"|"error";
type LockReason="login"|"expired"|"logout"|"identity";
const TeamSessionContext=createContext<SessionPacket|null>(null);
export const useTeamSession=()=>useContext(TeamSessionContext);
export default function AccessShell({children,publicPreview=false}:{children:(workspaceKey:string)=>ReactNode;publicPreview?:boolean}){
  const [status,setStatus]=useState<Status>(publicPreview?"legacy":"checking"),[session,setSession]=useState<SessionPacket|null>(null),[error,setError]=useState("");
  const [username,setUsername]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[workspaceKey,setWorkspaceKey]=useState(publicPreview?"public-preview":"legacy"),[hasWorkspace,setHasWorkspace]=useState(false),[lockReason,setLockReason]=useState<LockReason>("login");
  const workspaceIdentity=useRef<string|null>(null),statusRef=useRef(status),sessionRef=useRef(session),rechecking=useRef(false);
  statusRef.current=status;sessionRef.current=session;
  const lock=(reason:LockReason,message="")=>{clearExpectedSession();setLockReason(reason);setError(message);setStatus("locked");};
  const accept=(next:SessionPacket)=>{const identity=sessionIdentity(next);setExpectedSession(next);if(workspaceIdentity.current!==identity){workspaceIdentity.current=identity;setWorkspaceKey(`${identity}:${crypto.randomUUID()}`);}setSession(next);setHasWorkspace(true);setLockReason("login");setStatus("ready");setError("");};
  useEffect(()=>{if(publicPreview)return;let active=true;accessMode().then(async(mode:AccessModePacket)=>{if(!active)return;if(mode.mode==="legacy_loopback"){setStatus("legacy");return;}const value=await currentSession();if(!active)return;value?accept(value):setStatus("locked");}).catch(e=>{if(active){setError(e instanceof Error?e.message:"접근 모드 확인 실패");setStatus("error");}});const expired=()=>{if(active)lock("expired");};const rejected=()=>{if(active)setError("변경 요청이 거부되었습니다. 내용은 자동 재전송되지 않았습니다. 세션을 확인한 뒤 직접 다시 실행하세요.");};const mismatched=()=>{if(active)lock("identity","다른 탭에서 계정 또는 팀 세션이 바뀌었습니다. 이전 작업은 전송하지 않았습니다. 다시 로그인하거나 페이지를 새로고침하세요.");};window.addEventListener("trialboard:session-expired",expired);window.addEventListener("trialboard:write-rejected",rejected);window.addEventListener("trialboard:session-context-mismatch",mismatched);return()=>{active=false;window.removeEventListener("trialboard:session-expired",expired);window.removeEventListener("trialboard:write-rejected",rejected);window.removeEventListener("trialboard:session-context-mismatch",mismatched);};},[publicPreview]);
  useEffect(()=>{if(publicPreview||status!=="ready"||!session)return;const timer=window.setTimeout(()=>lock("expired"),Math.min(expiryDelay(session),2_147_000_000));return()=>window.clearTimeout(timer);},[publicPreview,status,session]);
  useEffect(()=>{if(publicPreview)return;const visible=async()=>{if(document.visibilityState!=="visible"||statusRef.current!=="ready"||rechecking.current)return;rechecking.current=true;try{const next=await currentSession();if(!next){lock("expired");return;}const previous=sessionRef.current;if(!previous||sessionIdentity(previous)!==sessionIdentity(next)){lock("identity","다른 탭에서 계정 또는 팀 세션이 바뀌었습니다. 이전 작업은 전송하지 않았습니다. 다시 로그인하거나 페이지를 새로고침하세요.");return;}accept(next);}catch{lock("identity","세션을 다시 확인하지 못해 작업공간을 잠갔습니다. 연결을 확인한 뒤 다시 로그인하세요.");}finally{rechecking.current=false;}};document.addEventListener("visibilitychange",visible);return()=>document.removeEventListener("visibilitychange",visible);},[publicPreview]);
  async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError("");try{accept(await login(username,password));setPassword("");}catch(e){setError(e instanceof Error?e.message:"로그인 실패");}finally{setBusy(false);}}
  async function leave(){setBusy(true);setError("");try{await logout();clearExpectedSession();setLockReason("logout");setStatus("locked");setSession(null);}catch(e){setError(e instanceof Error?e.message:"로그아웃 실패");}finally{setBusy(false);}}
  if(status==="checking")return <main className="access-loading" aria-busy="true"><BrandLogo/><CircularProgress size={24}/><p>접근 모드를 확인하는 중</p></main>;
  if(status==="error")return <main className="access-panel"><BrandLogo/><Alert severity="error">{error}</Alert><Button onClick={()=>location.reload()}>서버 설정 다시 확인</Button></main>;
  if(status==="legacy")return <TeamSessionContext.Provider value={null}>{children(publicPreview?"public-preview":"legacy")}</TeamSessionContext.Provider>;
  const title=lockReason==="expired"?"세션이 만료되었습니다":lockReason==="logout"?"로그아웃되었습니다":lockReason==="identity"?"세션이 변경되었습니다":"팀 작업공간 로그인";
  return <div className="access-root">
    {hasWorkspace&&<div className="access-workspace" hidden={status!=="ready"}><div className="team-strip"><span><strong>{session?.team.name}</strong> · {session?.subject.username} · {session?.role}</span><span>프로젝트별 팀 전체/제한 공유 · 로컬 TEAM 모드 · 운영 보안 구성 아님</span><Button size="small" onClick={()=>void leave()} disabled={busy}>로그아웃</Button></div>{error&&<Alert className="team-session-alert" severity="error">{error}</Alert>}<TeamSessionContext.Provider value={session}>{children(workspaceKey)}</TeamSessionContext.Provider></div>}
    {status==="locked"&&<main className="access-panel"><BrandLogo/><div><h1>{title}</h1><p>{hasWorkspace?"같은 계정으로 다시 로그인하면 편집 중인 화면을 이어갑니다.":"서버에서 발급한 세션 쿠키로 팀 자료에 접근합니다."}</p></div>{error&&<Alert severity="error">{error}</Alert>}<form onSubmit={submit}><TextField label="아이디" value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required/><TextField label="비밀번호" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><Button type="submit" variant="contained" disabled={busy}>{busy?"확인 중":"로그인"}</Button></form><small>다른 사용자나 팀으로 로그인하면 이전 작업 화면은 초기화됩니다. 이미 내려받은 파일은 로그아웃이나 권한 회수로 삭제할 수 없습니다.</small></main>}
  </div>;
}
