import {useEffect,useRef,useState} from "react";
import {Alert,Button,MenuItem,TextField} from "@mui/material";
import {MessageSquareText,ShieldCheck} from "lucide-react";
import {useTeamSession} from "./AccessShell";
import {projectRequest,type ProjectReceipt} from "./project-checkpoint";
import {readReviewAppend,readReviewFeed,responseMatches,type EventKind,type ReviewEvent} from "./team-collaboration";

const receiptKey=(receipt:ProjectReceipt)=>`${receipt.project_id}:${receipt.revision}`;

export default function TeamReviewPanel({receipt,locked}:{receipt:ProjectReceipt;locked:boolean}){
  const session=useTeamSession(),[events,setEvents]=useState<ReviewEvent[]>([]),[revision,setRevision]=useState(0),[kind,setKind]=useState<EventKind>("note"),[text,setText]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false);const generation=useRef(0),currentKey=useRef(receiptKey(receipt)),drafts=useRef(new Map<string,string>());currentKey.current=receiptKey(receipt);
  const canWrite=(session?.role==="admin"||session?.role==="reviewer")&&!(receipt.sharing_scope==="restricted"&&receipt.access_source==="read");
  async function refresh(){const requestGeneration=generation.current,key=receiptKey(receipt),projectId=receipt.project_id,documentRevision=receipt.revision;setBusy(true);setError("");try{const value=readReviewFeed(await projectRequest(`/api/projects/${encodeURIComponent(projectId)}/${documentRevision}/events`),projectId,documentRevision);if(!responseMatches(requestGeneration,generation.current,key,currentKey.current))return;setEvents(value.events);setRevision(value.event_revision);setConflict(false);}catch(e){if(responseMatches(requestGeneration,generation.current,key,currentKey.current))setError(e instanceof Error?e.message:"검토 이력을 불러오지 못했습니다.");}finally{if(responseMatches(requestGeneration,generation.current,key,currentKey.current))setBusy(false);}}
  useEffect(()=>{generation.current++;const key=receiptKey(receipt);currentKey.current=key;setEvents([]);setRevision(0);setError("");setNotice("");setConflict(false);setText(drafts.current.get(key)??"");void refresh();return()=>{generation.current++;};},[receipt.project_id,receipt.revision]);
  async function submit(){if(!text.trim()||busy||!canWrite)return;const requestGeneration=generation.current,key=receiptKey(receipt),projectId=receipt.project_id,documentRevision=receipt.revision,submitted=text.trim(),submittedKind=kind;drafts.current.set(key,text);setBusy(true);setError("");setNotice("");try{const event=readReviewAppend(await projectRequest(`/api/projects/${encodeURIComponent(projectId)}/${documentRevision}/events`,JSON.stringify({expected_revision:revision,kind:submittedKind,text:submitted,base_document_revision:documentRevision})),projectId,documentRevision);if(!responseMatches(requestGeneration,generation.current,key,currentKey.current))return;setEvents(rows=>[...rows,event]);setRevision(event.event_revision);setText("");drafts.current.delete(key);setNotice(submittedKind==="review_approval"?"워크플로 검토 확인을 기록했습니다. 임상 승인이 아닙니다.":"공동 검토 메모를 기록했습니다.");}catch(e){if(!responseMatches(requestGeneration,generation.current,key,currentKey.current))return;if(e instanceof Error&&e.message==="REVIEW_VERSION_CONFLICT"){setConflict(true);setError("다른 팀원이 먼저 기록했습니다. 작성 중인 내용은 유지했습니다. 최신 이력을 불러온 뒤 다시 저장하세요.");}else setError(e instanceof Error?e.message:"검토 기록 실패");}finally{if(responseMatches(requestGeneration,generation.current,key,currentKey.current))setBusy(false);}}
  return <section className="team-review" aria-label="팀 공동 검토"><header><div><span className="document-kicker">팀 공동 검토 · 검토 revision {receipt.revision}</span><h3>인증된 검토 이력</h3></div><MessageSquareText size={22}/></header><p>{receipt.sharing_scope==="restricted"?"허용된 프로젝트 구성원만 읽습니다.":"현재 팀 전체가 읽습니다."} reviewer와 admin은 프로젝트 쓰기 권한 범위에서 기록할 수 있으며 모든 기록은 추가 전용입니다. 이 revision은 같은 PDF의 검토 기록이며 새 PDF 문서 버전이 아닙니다.</p>{error&&<Alert severity="error" action={conflict?<Button onClick={()=>void refresh()}>최신 이력 불러오기</Button>:undefined}>{error}</Alert>}{notice&&<Alert severity="success">{notice}</Alert>}<div className="team-review-compose"><TextField select size="small" label="기록 종류" value={kind} onChange={e=>setKind(e.target.value as EventKind)} disabled={!canWrite||busy||locked}><MenuItem value="note">검토 메모</MenuItem><MenuItem value="review_approval">워크플로 검토 확인</MenuItem></TextField><TextField multiline minRows={2} label="검토 내용" value={text} onChange={e=>{setText(e.target.value);drafts.current.set(currentKey.current,e.target.value);}} disabled={!canWrite||busy||locked} slotProps={{htmlInput:{maxLength:4000}}}/><Button variant="contained" disabled={!canWrite||busy||locked||!text.trim()} onClick={()=>void submit()}>기록 추가</Button></div>{!canWrite&&<Alert severity="info">viewer는 문서와 이력을 읽을 수 있지만 메모·검토 확인은 추가할 수 없습니다.</Alert>}<div className="team-review-history">{!events.length&&<p>아직 공동 검토 기록이 없습니다.</p>}{events.map(event=><article key={event.event_revision}><ShieldCheck size={17}/><div><strong>{event.kind==="review_approval"?"워크플로 검토 확인":"검토 메모"} · {event.subject.username}</strong><p>{event.text}</p><small>이력 {event.event_revision} · 검토 revision {event.base_document_revision} · {new Date(event.created_at).toLocaleString("ko-KR")} · 임상 승인 아님</small></div></article>)}</div></section>;
}
